In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("beam_data_1.csv")
df.head()

Elastic_Modulus (GPa)  Load (kN)  Length_of_Beam (m)  \
0                    151          2                  11   
1                    158          3                   7   
2                    158          4                   5   
3                    141          1                  15   
4                    177          4                  13   

   X-sectional Width b (mm)  X-sectional Height h (mm)  Max Deflection (mm)  
0                        58                         95             88.62827  
1                        61                         88             39.16701  
2                        36                         91             29.16260  
3                        31                         84            325.68300  
4                        62                        106            168.09220

In [3]:
df.iloc[0:1,:]

Elastic_Modulus (GPa)  Load (kN)  Length_of_Beam (m)  \
0                    151          2                  11   

   X-sectional Width b (mm)  X-sectional Height h (mm)  Max Deflection (mm)  
0                        58                         95             88.62827

In [4]:
## Function for loading the data and train test split

def data_preprocessing(csv_file,train_size,test_size,The_target_variable):
    
    # load the data using pandas
    
    df = pd.read_csv(csv_file)
    
    print(f"The shape of your dataset is : {df.shape}")
    
    total_no_of_rows = df.shape[0]
    total_no_of_columns = df.shape[1]
    
    # The input features(dependent features) & The target variable(independent feature)
    
    X = df.drop(The_target_variable,axis = 1)
    y = df[[The_target_variable]]
    
    # Train_test_split
    
    no_of_rows_for_training = total_no_of_rows*(train_size/100)
    no_of_rows_for_testing = total_no_of_rows*(test_size/100)
    
    train_X = X.iloc[0:int(no_of_rows_for_training),:] 
    test_X = X.iloc[int(no_of_rows_for_training):total_no_of_rows,:]
 
    train_y = y.iloc[1:int(no_of_rows_for_training),:]
    test_y = y.iloc[int(no_of_rows_for_training):total_no_of_rows,:]
    
    print(f"The shape of your traing data set is: {train_X.shape}")
    print(f"The shape of your testing data set is : {test_X.shape}")
    
    ## Convert the pandas dataframe to to Numpy array to do model building
    
    train_X_arr = train_X.to_numpy()
    train_y_arr = train_y.to_numpy()
    test_X_arr = test_X.to_numpy()
    test_y_arr = test_y.to_numpy()
    
    print("your dataframe has been splitted to a traing and testing dataset as well as it has been converted to numpy array for furthe preprocessing")
    
    return train_X_arr, train_y_arr, test_X_arr, test_y_arr
    

In [5]:
train_X_arr, train_y_arr, test_X_arr, test_y_arr = data_preprocessing("beam_data_1.csv",75,25,"Max Deflection (mm)")

The shape of your dataset is : (10000, 6)
The shape of your traing data set is: (7500, 5)
The shape of your testing data set is : (2500, 5)
your dataframe has been splitted to a traing and testing dataset as well as it has been converted to numpy array for furthe preprocessing


In [6]:
def computing_cost_fn_ridge(feature_matrix, target_var, weight_matrix):
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    X = np.hstack((ones_column, feature_matrix))
    y = target_var

    no_of_samples = X.shape[0]
    no_of_columns = X.shape[1]
    
    summation = 0.0
    
    weight_sum = 0.0
    
    
    for x,y in zip(X, y):
        y_hat = np.dot(x,weight_matrix)
        summation += (y_hat - y) ** 2
        
    for w in weights:
        weight_sum += w ** 2
        
        
    final_cost = (summation / (no_of_samples * 2.0)) + (weight_sum / no_of_columns)

    return final_cost[0]

In [7]:
# weights = np.zeros((train_X_arr.shape[1] + 1,train_y_arr.shape[1]))
weights = np.ones(train_X_arr.shape[1] + 1,).reshape(1,-1).T * 0.6
weights

array([[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]])

In [8]:
sum = 0.0

for i in weights:
    sum = sum + (i/abs(i))
    
print(sum)
    

[6.]


In [9]:
# computing_cost_fn_ridge(train_X_arr, train_y_arr, weights)

In [10]:
def gradient_descent_ridge(feature_matrix, target_var, weight_matrix,learning_rate,max_iter):
    
    iteration = 0
    
    cost = np.zeros(((max_iter),1))
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    
    X = np.hstack((ones_column, feature_matrix))
    
    no_of_samples = X.shape[0]
    
    no_of_columns = X.shape[1]
    
    
    while iteration < max_iter:
        
        gradient = np.zeros((X.shape[1],)).reshape(1,-1).T
        
        cost[iteration] = computing_cost_fn_ridge(feature_matrix, target_var, weight_matrix)
        
        for x,y in zip(X, target_var):
            
            y_hat = np.dot(x,weight_matrix)
            
            gradient = gradient + ((y_hat[0] - y[0]) * x.reshape(1,-1).T)  # gradient calculation
            
        
            
        weight_sum = 0.0
        
        for w in weights:
            
            weight_sum += w 
            
               
        weight_matrix -= (learning_rate * ((gradient /no_of_samples) + ((weight_sum)/(2.0*no_of_columns)) ))  # updation of weight matrix
        
#         print("Iteration:", iteration, "Cost:", cost[iteration], "Weights:", weight_matrix)
        
        if iteration > 0 and np.abs(cost[iteration - 1] - cost[iteration]) < 1e-5:
            
            print("cost convergence")
            
            break
        
        iteration = iteration + 1
        
        
    return cost , weight_matrix 

In [11]:
# gradient_descent_ridge(train_X_arr,train_y_arr,weights,0.00001,50)

In [12]:
# computing_cost_fn_ridge(train_X_arr, train_y_arr, weights)

In [13]:
def computing_cost_fn_lasso(feature_matrix, target_var, weight_matrix):
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    X = np.hstack((ones_column, feature_matrix))
    y = target_var

    no_of_samples = X.shape[0]
    no_of_columns = X.shape[1]
    
    summation = 0.0
    
    weight_sum = 0.0
    
    
    for x,y in zip(X, y):
        y_hat = np.dot(x,weight_matrix)
        summation += (y_hat - y) ** 2
        
    for w in weights:
        weight_sum += abs(w)
        
        
    final_cost = (summation / (no_of_samples * 2.0)) + (weight_sum / no_of_columns)

    return final_cost[0]

In [14]:
# computing_cost_fn_lasso(train_X_arr, train_y_arr, weights)

In [15]:
def gradient_descent_lasso(feature_matrix, target_var, weight_matrix,learning_rate,max_iter):
    
    iteration = 0
    
    cost = np.zeros(((max_iter),1))
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    
    X = np.hstack((ones_column, feature_matrix))
    
    no_of_samples = X.shape[0]
    
    no_of_columns = X.shape[1]
    
    
    while iteration < max_iter:
        
        gradient = np.zeros((X.shape[1],)).reshape(1,-1).T
        
        cost[iteration] = computing_cost_fn_lasso(feature_matrix, target_var, weight_matrix)
        
        for x,y in zip(X, target_var):
            
            y_hat = np.dot(x,weight_matrix)
            
            gradient = gradient + ((y_hat[0] - y[0]) * x.reshape(1,-1).T)  # gradient calculation
            
        
            
        weight_sum = 0.0
        
        for w in weights:
            
            weight_sum += w/abs(w) 
            
               
        weight_matrix -= (learning_rate * ((gradient /no_of_samples) + ((weight_sum[0])/no_of_columns) ))  # updation of weight matrix
        
#         print("Iteration:", iteration, "Cost:", cost[iteration], "Weights:", weight_matrix)
        
        if iteration > 0 and np.abs(cost[iteration - 1] - cost[iteration]) < 1e-5:
            
            print("cost convergence")
            
            break
        
        iteration = iteration + 1
        
        
    return cost , weight_matrix 

In [16]:
# gradient_descent_lasso(train_X_arr,train_y_arr,weights,0.00001,10)

In [17]:
# def compute_cost_poly_basis(feature_matrix, target_var, weight_matrix, degree):
#     """
#     Compute the cost function for polynomial basis functions.

#     Parameters:
#     - feature_matrix: Input feature matrix (numpy array)
#     - target_var: Target variable (numpy array)
#     - weight_matrix: Coefficient matrix (numpy array)
#     - degree: Degree of the polynomial basis function

#     Returns:
#     - final_cost: The computed cost (scalar)
#     """

#     # Add a column of ones to the feature matrix
#     ones_column = np.ones((feature_matrix.shape[0], 1))
#     X = np.hstack((ones_column, feature_matrix))
    
#     print(X)
    
#     d = 0
    
#     for x in X:
#         new_arr = np.power(x,d)
#         x[d] = new_arr
#         x = np.power(x,d)
#         d = d+1
        
#     print("change")
#     print(X)

#     y = target_var
#     no_of_samples = X.shape[0]

#     # Calculate the cost
#     summation = 0.0
#     for x, y in zip(X, y):
#         y_hat = np.dot(x, weight_matrix)
#         summation += (y_hat - y) ** 2

#     final_cost = summation / (no_of_samples * 2.0)

#     return final_cost[0]

# # Example usage:
# # Assuming you have feature_matrix, target_var, and weight_matrix defined
# degree = 2  # Example degree for the polynomial basis function
# cost = compute_cost_poly_basis(train_X_arr,train_y_arr, weights, degree)
# print("Cost:", cost)

In [18]:
def convert_input_poly(X):
    
    no_of_samples = X.shape[0]
    
    no_of_columns = X.shape[1]
    
    pre_final_matrix = np.ones((no_of_columns,no_of_samples))
    
    d = 0
    
    for x in X.T:
        
        pre_final_matrix[d,:] =  np.power(x,d).reshape(1,-1)
        
        d = d + 1
        
    final_matrix = pre_final_matrix.T
    
    return final_matrix
        
    
    

In [19]:
weights1 = np.ones(train_X_arr.shape[1] + 1,).reshape(1,-1).T * 0
weights1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
def computing_cost_fn_poly(feature_matrix, target_var, weight_matrix):
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    X_in = np.hstack((ones_column, feature_matrix))
    y = target_var
    
    X = convert_input_poly(X_in)

    no_of_samples = X.shape[0]
    
    summation = 0.0;
    
    
    for x,y in zip(X, y):
        y_hat = np.dot(x,weight_matrix)
        summation += (y_hat - y) ** 2
        
    final_cost = summation / (no_of_samples * 2.0)

    return final_cost[0]

In [21]:
def gradient_descent_poly(feature_matrix, target_var, weight_matrix,learning_rate,max_iter):
    
    iteration = 0
    
    cost = np.zeros(((max_iter),1))
    
    ones_column = np.ones((feature_matrix.shape[0], 1))
    
    X_in = np.hstack((ones_column, feature_matrix))
    
    X = convert_input_poly(X_in)
    
    no_of_samples = X.shape[0]
    
    
    while iteration < max_iter:
        
        gradient = np.zeros((X.shape[1],)).reshape(1,-1).T
        
        cost[iteration] = computing_cost_fn_poly(feature_matrix, target_var, weight_matrix)
        
        for x,y in zip(X, target_var):
            
            y_hat = np.dot(x,weight_matrix)
            
            gradient = gradient + ((y_hat[0] - y[0]) * x.reshape(1,-1).T)  # gradient calculation
            
        
               
        weight_matrix -= (learning_rate * (gradient)/no_of_samples) # updation of weight matrix
        
        if iteration > 0 and np.abs(cost[iteration - 1] - cost[iteration]) < 1e-4:
            
            print("cost convergence")
            
            break
        
        iteration = iteration + 1
        
        
    return cost , weight_matrix 

In [22]:
computing_cost_fn_poly(train_X_arr, train_y_arr, weights1)

38285.00043349855

In [23]:
gradient_descent_poly(train_X_arr, train_y_arr, weights1,1e-20,2000)

(array([[38285.0004335 ],
        [24971.62471908],
        [24683.89044309],
        ...,
        [24676.55051407],
        [24676.55002143],
        [24676.5495288 ]]),
 array([[6.02941616e-16],
        [8.95210750e-14],
        [6.28296020e-15],
        [8.79281300e-13],
        [4.45634818e-09],
        [1.78584190e-08]]))