In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [29]:
df = pd.read_csv("beam_data_1.csv")
df.head()

Elastic_Modulus (GPa)  Load (kN)  Length_of_Beam (m)  \
0                    151          2                  11   
1                    158          3                   7   
2                    158          4                   5   
3                    141          1                  15   
4                    177          4                  13   

   X-sectional Width b (mm)  X-sectional Height h (mm)  Max Deflection (mm)  
0                        58                         95             88.62827  
1                        61                         88             39.16701  
2                        36                         91             29.16260  
3                        31                         84            325.68300  
4                        62                        106            168.09220

In [32]:
df.iloc[0:1,:]

Elastic_Modulus (GPa)  Load (kN)  Length_of_Beam (m)  \
0                    151          2                  11   

   X-sectional Width b (mm)  X-sectional Height h (mm)  Max Deflection (mm)  
0                        58                         95             88.62827

In [33]:
## Function for loading the data and train test split

def data_preprocessing(csv_file,train_size,test_size,The_target_variable):
    
    # load the data using pandas
    
    df = pd.read_csv(csv_file)
    
    print(f"The shape of your dataset is : {df.shape}")
    
    total_no_of_rows = df.shape[0]
    total_no_of_columns = df.shape[1]
    
    # The input features(dependent features) & The target variable(independent feature)
    
    X = df.drop(The_target_variable,axis = 1)
    y = df[[The_target_variable]]
    
    # Train_test_split
    
    no_of_rows_for_training = total_no_of_rows*(train_size/100)
    no_of_rows_for_testing = total_no_of_rows*(test_size/100)
    
    train_X = X.iloc[0:int(no_of_rows_for_training),:] 
    test_X = X.iloc[int(no_of_rows_for_training):total_no_of_rows,:]
 
    train_y = y.iloc[1:int(no_of_rows_for_training),:]
    test_y = y.iloc[int(no_of_rows_for_training):total_no_of_rows,:]
    
    print(f"The shape of your traing data set is: {train_X.shape}")
    print(f"The shape of your testing data set is : {test_X.shape}")
    
    ## Convert the pandas dataframe to to Numpy array to do model building
    
    train_X_arr = train_X.to_numpy()
    train_y_arr = train_y.to_numpy()
    test_X_arr = test_X.to_numpy()
    test_y_arr = test_y.to_numpy()
    
    print("your dataframe has been splitted to a traing and testing dataset as well as it has been converted to numpy array for furthe preprocessing")
    
    return train_X_arr, train_y_arr, test_X_arr, test_y_arr
    

In [34]:
data_preprocessing("beam_data_1.csv",75,25,"Max Deflection (mm)")

The shape of your dataset is : (10000, 6)
The shape of your traing data set is: (7500, 5)
The shape of your testing data set is : (2500, 5)
your dataframe has been splitted to a traing and testing dataset as well as it has been converted to numpy array for furthe preprocessing


(array([[151,   2,  11,  58,  95],
        [158,   3,   7,  61,  88],
        [158,   4,   5,  36,  91],
        ...,
        [180,   2,   6,  66,  93],
        [139,   1,  10,  31,  94],
        [125,   5,  14,  65,  81]], dtype=int64),
 array([[ 39.16701 ],
        [ 29.1626  ],
        [325.683   ],
        ...,
        [ 11.302083],
        [ 69.85218 ],
        [794.35693 ]]),
 array([[168,   1,  14,  51, 103],
        [174,   4,  10,  38,  95],
        [144,   4,  12,  61, 103],
        ...,
        [186,   2,  13,  54,  95],
        [120,   3,  12,  52, 107],
        [176,   5,  11,  68,  86]], dtype=int64),
 array([[ 73.27115],
        [176.3991 ],
        [180.02786],
        ...,
        [127.56236],
        [169.53879],
        [218.56023]]))