In [5]:
!pip install torch
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

In [2]:
!nvidia-smi


Wed Jan 17 19:03:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Tensors

In [4]:
import torch
import numpy as np

## Basic Operations

In [ ]:
torch.tensor([[1,-1],[1,-1]])  ## A 2d tensor with 2 rows and 2 columns

tensor([[ 1, -1],
        [ 1, -1]])

In [ ]:
torch.randn(3,4)   ## 2 cross 4 tensor withh random values

tensor([[ 1.1895, -0.2915, -0.2431,  0.5798],
        [-1.5710,  1.9543,  0.1597, -1.0622],
        [ 0.4250, -0.8319, -0.2319,  1.6430]])

In [ ]:
torch.randn(2,3,4)  ## A 3d tensor with random values

tensor([[[-0.8407,  0.3941,  0.4242, -0.8886],
         [ 0.8045,  0.7075, -0.6028, -0.8471],
         [-1.0436, -0.4117, -1.5164, -2.5456]],

        [[ 1.6180,  0.3006, -1.7536, -1.8600],
         [-1.9945,  0.7010,  0.3133, -0.3872],
         [ 0.2274,  0.5429,  0.7714,  0.3943]]])

In [ ]:
torch.tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10]])  ## A 2d tensor with 3 rows and 4 columns

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [ ]:
torch.tensor([[[1,-1],[1,-1]],[[1,-2],[2,-1]]])  ## A 3d tensor

tensor([[[ 1, -1],
         [ 1, -1]],

        [[ 1, -2],
         [ 2, -1]]])

In [ ]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))  ## we can create tensors from numpy array

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
# cuda0 = torch.device('cuda:0')
# torch.ones([2, 4], dtype=torch.float64, device=cuda0)

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])

tensor(6)


In [ ]:
x[0][1] = 8   ## We can create a tensor with the value of a spectfied position
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


In [6]:
import time

a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

t0 = time.time()
a.matmul(b)
tn = time.time()

print("cpu",(tn-t0))

cpu 25.937257051467896


In [10]:
a = torch.rand(10000,10000).to("cuda")
b = b.cuda()

t0 = time.time()
a.matmul(b)

tn = time.time()
print((tn-t0))

0.0002579689025878906
