In [1]:
pip install torch


Note: you may need to restart the kernel to use updated packages.


# Tensors

In [2]:
import torch
import numpy as np

## Basic Operations

In [3]:
torch.tensor([[1,-1],[1,-1]])  ## A 2d tensor with 2 rows and 2 columns

tensor([[ 1, -1],
        [ 1, -1]])

In [4]:
torch.tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10]])  ## A 2d tensor with 3 rows and 4 columns

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [5]:
torch.tensor([[[1,-1],[1,-1]],[[1,-2],[2,-1]]])  ## A 3d tensor

tensor([[[ 1, -1],
         [ 1, -1]],

        [[ 1, -2],
         [ 2, -1]]])

In [7]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))  ## we can create tensors from numpy array

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [8]:
 torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [11]:
# cuda0 = torch.device('cuda:0')
# torch.ones([2, 4], dtype=torch.float64, device=cuda0)

In [16]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])

tensor(6)


In [18]:
x[0][1] = 8   ## We can create a tensor with the value of a spectfied position
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])
