In [3]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118Note: you may need to restart the kernel to use updated packages.

     ---------------------------------------- 4.9/4.9 MB 12.5 MB/s eta 0:00:00
     ---------------------------------------- 3.9/3.9 MB 17.9 MB/s eta 0:00:00
     ---------------------------------------- 2.7/2.7 GB ? eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1


In [35]:
import torch
import matplotlib.pyplot as plt

In [36]:
x1 = torch.tensor([1,2,3,4,5])
x1

tensor([1, 2, 3, 4, 5])

In [37]:
x2 = torch.randint(0,50,(10,))
x2

tensor([25, 10, 13, 22, 20,  2,  7, 49, 16, 29])

In [38]:
x3 = torch.randint(0,50,(10,5))
x3

tensor([[12, 25, 20,  4, 47],
        [ 7, 41,  7,  9, 35],
        [11, 35, 27, 13, 15],
        [34,  3,  5, 49,  6],
        [ 9,  1, 29, 49, 38],
        [33,  7,  7, 25,  2],
        [14, 15, 33,  9,  2],
        [41, 49,  4,  8, 17],
        [39, 28, 40, 30, 10],
        [26, 41, 48,  7, 26]])

In [32]:
import time

a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

t0 = time.time()
a.matmul(b)
tn = time.time()

print("cpu",(tn-t0))

cpu 18.662341594696045


In [40]:
a = torch.rand(10000,10000).to("cuda")
b = b.cuda()

t0 = time.time()
a.matmul(b)

tn = time.time
print("Gpu",(tn-t0))

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [30]:
tr_sample = 1000

x1 = 1 + 4*torch.rand(tr_sample,1)
x2 = 100 + 

torch.Size([10000, 10000])

In [6]:
import torch

In [5]:
print(torch.cuda.device_count())

0


In [7]:
torch.__version__


'2.1.2+cu118'

In [8]:
conda uninstall pytorch

Solving environment: ...working... failed

Note: you may need to restart the kernel to use updated packages.



PackagesNotFoundError: The following packages are missing from the target environment:
  - pytorch




In [ ]:
torch.__version